{% set version = "0.21.0" %}

package:
  name: openpiv
  version: {{ version }}

source:
  fn: openpiv-{{ version }}.tar.gz
  url: https://github.com/OpenPIV/openpiv-python/archive/{{ version }}.tar.gz
  sha256: 09747e5a49bede8547c0b8a2b6db8ac96afdaad9f9528f358349f47aeca6b7fd
  
build:
  number: 0
  script: 
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - numpy >=1.7
    - scipy >=0.12
    - cython

  run:
    - python
    - setuptools
    - numpy >=1.7
    - scipy >=0.12
    - cython 
    - progressbar2
    - scikit-image

test:
  imports:
    - openpiv

about:
  home: https://github.com/openpiv/openpiv-python
  license: GPL 3
  license_file: LICENSE.txt
  summary: "Open Source Particle Image Velocimetry"
  doc_url: http://openpiv.readthedocs.io/

extra:
  recipe-maintainers:
    - alexlib
