{% set version = "0.26.1" %}
{% set python_min = "3.10" %}

package:
  name: openpiv
  version: {{ version }}

source:
  fn: openpiv-{{ version }}.tar.gz
  url: https://github.com/OpenPIV/openpiv-python/archive/v{{ version }}.tar.gz
  sha256: 2d3cffcd730bcab624e139bca158a6e8ce3da4c3b59e9666f0435f048a5cf539

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }}
    - numpy
    - scikit-image
    - imageio
    - matplotlib-base
    - scipy
    - natsort
    - tqdm

test:
  imports:
    - openpiv
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest -v --pyargs openpiv

about:
  home: https://github.com/openpiv/openpiv-python
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Open Source Particle Image Velocimetry
  doc_url: http://openpiv.readthedocs.io/

extra:
  recipe-maintainers:
    - alexlib
