{% set version = "0.23.6" %}

package:
  name: openpiv
  version: {{ version }}

source:
  fn: openpiv-{{ version }}.tar.gz
  url: https://github.com/OpenPIV/openpiv-python/archive/{{ version }}.tar.gz
  sha256: ef1eec8060f1d84196e6bd55f15886fa31f453d408031dbcf097346a9a761c4b

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - numpy
  run:
    - python >=3.7
    - {{ pin_compatible('numpy') }}
    - scikit-image
    - imageio
    - matplotlib-base
    - scipy
    - natsort

test:
  imports:
    - openpiv

about:
  home: https://github.com/openpiv/openpiv-python
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Open Source Particle Image Velocimetry
  doc_url: http://openpiv.readthedocs.io/

extra:
  recipe-maintainers:
    - alexlib
