appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fMkGjW0rG1549c1wOc2Sr0oYB7Tk5oLHzC1RPQReuxP8sHKwMJcVpFbJdtw3tB6US+whDFh5HuEROHjsfph1E9v1x1xwNyjhFmUl6f9gCXs8z0TGqeDw44ezsNnUR0QmVLhAoxlXQtwPEc5v9kYXWlrz/oPVCHDuaOOCwbrvwCGl1ElEgzeLHVysQ8kKZUxtv9AwzGPn7YWD91GNWFFcxlTf1lZG0dIA8x9q3o5wpmQhaGxzpM1PCIlJBvJMFyI5lIZyrKMWGt2TnZygESKQCqi2k+BHnqwZWX1hGpYzuz3J4VCu8roo8VJDwnLMF3AovFRf60rL6xtYS1/AD5mmsL5xb4mi1Ceycr98mpdUWqFTQ2sX9nD9pQxc9g6+a1y62ZRAFuCOS/b6P8eACGcOr+YQTRUnzZ+qGVtmSE/MeYrmiS9oGCnl3OkICuNDjAQZ+SJb/dy57McqpNPLqvGV8iDK17sV5s/7Pq4r2v4+TIIGQIjd1aXouYaNf7AjFDyM+0ReQ5aKCQptKUb5v55GVRwutwgSl89LxjZp4UGPeTyvjjSxmViBv44sw8bYuxknPBQ8574CdcqGcGmB40auTXMbvbptTEPByE1+E/LjNI8255k85dCvHtV68rGle6YAjpVpnCBTMNgKEmj8ou+UKC2jh9xUtVT+hmPXO+ux/1E=}
